// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Week 1: Theme',
      items: [
        {
          type: 'autogenerated',
          dirName: '1-week',
        },
      ],
    },
    {
      type: 'category',
      label: 'Week 2: Theme',
      items: [
        {
          type: 'autogenerated',
          dirName: '2-week',
        },
      ],
    },
    {
      type: 'category',
      label: 'Week 3: Theme',
      items: [
        {
          type: 'autogenerated',
          dirName: '3-week',
        },
      ],
    },
    {
      type: 'category',
      label: 'Week 4: Theme',
      items: [
        {
          type: 'autogenerated',
          dirName: '4-week',
        },
      ],
    },
    'insights',
  ],
  
};

module.exports = sidebars;