// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Today I Learned',
      items: [
        {
          type: 'autogenerated',
          dirName: 'til',
        },
      ],
    },

    {/*
      type: 'category',
      label: 'React.js',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react',
        },
      ],
    },
    {
      type: 'category',
      label: 'Next.js',
      items: [
        {
          type: 'autogenerated',
          dirName: 'next',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced',
        },
      ],
    */},
    'resources',
  ],
  
};

module.exports = sidebars;